### ISSUE TITLE
항공기 종방향 선형시스템 구현

### ISSUE THREAD

**Issue by hnlee77** [scKim33/linearADP#6]
[노션 페이지](https://www.notion.so/f552f833a8ac44d4971688aa0b2c2a87#1f8233a6cb7e4fb3b75db9952530c48b)에 첨부된 항공기 모델을 이용해 종방향 선형시스템을 구현하고 PID, LQR 제어기를 짜보기

### TODO
- [ ] 항공기 종방향 선형시스템 모델 구현
- [ ] PID 제어기 구현
- [ ] LQR 제어기 구현

**Comment by scKim33** [comment]
PID 제어기 구현 과정에서 질문이 있습니다
f18 모델의 경우 control input이 두가지로 존재하는데 하나의 PID 제어기로 두가지 control input에 대한 K 값을 구할 수 있는지, 아니면 추가적인 조치를 취해야 하는지 궁금합니다

**Comment by hnlee77** [comment]
각각의 Single input, single output에 대해 제어기를 구현해야합니다~

**Comment by scKim33** [comment]
single input, single output에 대해서 개념이 좀 헷갈려서 질문드립니다
f18 모델에서는 u1에 대한 PID, u2에 대한 PID를 각각 구현해서, 시뮬레이션 루프에 같은 x_ref를 사용하는 두 개의 PID로 u1, u2를 각각 계산하고 이를 ode solver에 넣어주어야 한다는 의미인가요?
그리고 single output은 x_ref 값을 벡터(가령, y=Cx 꼴)가 아닌 x의 특정 성분에 대한 reference 값인 스칼라로 두어야 한다는 뜻인가요?

**Comment by hnlee77** [comment]
수정 후 풀리퀘를 올려주세요~
